### ISSUE TITLE
Can you tell me how did you create this program?

### ISSUE THREAD

**Issue by Species-8472** [gdkchan/HDATextTool#4]
Can you explain me how did you create this program? And how did you knew that in .HDA files are hidden .bin files?

**Comment by gdkchan** [comment]
I analyzed the file on a hex editor and was clear that the file is a container (because you can see stuff like offsets and lengths on the header). To figure out the compression I just ran the game on a PS2 emulator and set a breakpoint on the memory address where the game was writing the uncompressed text that was showing up on the screen. The emulator then broke execution when the game started to write uncompressed data, and I could analyze the decompression subroutine disasm step by step. After this I wrote equivalent C# code to decompress the files.

Through observation I also discovered that a bit on the hda files was used to tell if the files are compressed or not, so I could just clear the bit and store the files uncompressed (no need to write a compressor).

The LBAs on the elf I discovered because when I changed the size of the file the game used to crash. So it was pretty obvious that the LBA changes was messing the game. Searched the LBAs inside the ELF file and I was able to quickly find a LBA table, so it was just matter of implementing an extra feature on the tool to automatically patch those on the ELF too, and now the game was fully working.

**Comment by Species-8472** [comment]
Thank you!

**Comment by Species-8472** [comment]
Thanks.

**Comment by Species-8472** [comment]
Thank you.

**Comment by Species-8472** [comment]
Thank you.

**Comment by Species-8472** [comment]
Thank you very much!

**Comment by Species-8472** [comment]
Thank you very much.

**Comment by Species-8472** [comment]
Wait... what did you ment by setting a breakpoint on the memory adress where the game was writing the uncompressed text that was showing up on the screen. How to know where in uncompressed text?

**Comment by gdkchan** [comment]
A _breakpoint_ is... well... _A point where the game stops running (breaks)_. On emulators with debugging features, you can make the game stop running when it tries writing to a given memory address, and this is useful so you know which piece of code is responsible for writing the DATA you're interested in. I was interested in knowing from where the text that appears on the screen comes from, so I naturally, added a breakpoint to the address where this text was located.

When you start playing the game, you'll see readable text showing on the screen. But if you look on the game files, you most likely will not find any readable text (this applies to other games too). This happens for a lot of different reasons. Sometimes the game developers don't want people tampering with the game files, so they do things like encrypting the data (changing the data so it is not readable by someone looking into the files with something like a hex viewer), this discourage modifications because cryptography often means that some extra work is needed to figure out both the algorithm and the key necessary to decrypt the file (make it readable again). this is NOT the case for this game through, Harvest Moon: Save the Homeland doesn't use ANY kind of cryptography, which is good.

It does use however, compression, which is way more common. Older games also often used it. Compression is used to reduce the size of the data. It works by removing repetitions on data, the algorithm must be able to find repeating patterns and shrink it to use less bytes. For example, let's say we have the phrase "I am so hungry that I could eat a very very very big cake". The word very is repeated twice on this phrase, so I could do something like this to make it smaller "I am so hungry that I could eat a very*3 big cake". Notice how I added a "*3" indicating that the word should appear three times. By doing that I just reduced 8 characters from the phrase, on a file this would be a 8 bytes reduction. This was just a silly example, but it's basically how compressions work. On real compressions, you have data on the file that indicates thing like, "this piece of text/data already appeared somehwere else? If so, where? (address, or number of bytes it needs to go back on the output stream to find the data usually), how many characters/bytes are repeated?".

Now going back to our silly example. If you show the text "I am so hungry that I could eat a very*3 big cake" to someone, they would probably like what the *3 is. Obviously the text is not very useful this way. So you need to bring the text back to its original form. This is called decompression. For this specific example, we could write a decompressor that searches for all * on the text, followed by a number (*N), and replace it by N repetitions of the word. By doing that we have "cake cake cake" again! The final result is our _uncompressed text_ So, basically, the uncompressed text is our original text, the text in it's _uncompressed form_.

**Comment by Species-8472** [comment]
Don't understand this how to find this text? How to find something like that I'm going to change, For ex. models, textures.  Where is address where is text located? And how to know any address where is anything I  need located?

**Comment by Species-8472** [comment]
How to know what is memory address of DATA I'm interested in it? 
Thank you I'm noob

**Comment by gdkchan** [comment]
I don't remember the address of the text. You can create a save state on a emulator at some part of the game with text, then extract the save state and look into the ram with a hex editor. Using the search feature you can find the text (and its address). For other data you need specific tools like tile viewers. I think you can view some texturas from the hdas after extracted with tile viewer (I remember being able to open the game font). For musics maybe they're in VAG format if youre lucky, there are some tools that handle this format.

**Comment by Species-8472** [comment]
Thank you very much! Hope you will make more awesome programs

**Comment by Species-8472** [comment]
Thanks! Hope you make more lovely programs

**Comment by Species-8472** [comment]
Hey pls tell me how to set breakpoint? How did you make tool to export .bin files from .HDA, or it is inside .HDA?

**Comment by Species-8472** [comment]
Why do you need breakpoint to know address when you know where is file located on harvest moon.iso? How to set breakpoint?  And how did you wrote C# code?

**Comment by gdkchan** [comment]
Closing because this is supposed to track real issues on the tool and not teaching people how to program or use advanced debugging tools. Check tutorials on the internet or use some specific forum to discuss such questions.
