### ISSUE TITLE
Problem fixing ELF

### ISSUE THREAD

**Issue by Tim1212** [gdkchan/HDATextTool#9]
I used to fix elf without any problem. So all was normal at the start when i had smaller EVTMSG00.HDA, but now when EVTSMG00.HDA file is bigger, I first use "hdatexttool -fixelf SLUS_202.51 310 172368", and it works fine, but then i need to use and i use this command "hdatexttool -fixelf SLUS_202.51 27391 84096" It fails with this message "The LBA you entered was not found on the table!" Before when EVTMSG00.HDA file was smaller i use both of commands and there was no problem fixing elf... But now like this
 on the pic![untitled](https://cloud.githubusercontent.com/assets/25753888/24740897/b6458dd4-1aa3-11e7-8aa2-f705e70ff359.png)

**Comment by gdkchan** [comment]
This means that the LBA you entered was not found. You need to take into account the new lba after you use the fixelf command. I recommend that you always do the process on a clean image file and then use the commands since you're less likely to make mistakes this way.

**Comment by Tim1212** [comment]
Thanks alot!

**Comment by gdkchan** [comment]
Also if you need to "fix" mora than one LBA, it's better to start with LBAs with bigger values (like the 27391) and then go down to the smaller ones (like 310, which is less than 27391). Because LBAs are stored in ascending order on the table, so "fixing" smaller LBAs will change the LBAs that comes after it too, but the opposite doesn't happen.
